# Generated by Django 3.0 on 2019-12-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.CharField(max_length=50)),
                ('cName', models.CharField(max_length=20)),
                ('student_number', models.CharField(max_length=10)),
                ('room', models.CharField(max_length=20)),
                ('item', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(default='未處理', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
            ],
        ),
    ]
