# Generated by Django 3.0 on 2019-12-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func5api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='uid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
