# Generated by Django 3.0 on 2019-12-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func5api', '0002_auto_20191219_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='fix',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
