# Generated by Django 3.0 on 2019-12-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func5api', '0005_auto_20191224_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fix',
            name='status',
            field=models.CharField(choices=[('status', '未處理'), ('status', '已處理')], default='未處理', max_length=10),
        ),
    ]
